<?xml version="1.0" encoding="UTF-8"?>
<project name="bank_management" default="run" basedir=".">
    <description>Builds, tests, and runs the project bank_management.</description>

    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="lib.dir" value="lib"/>

    <path id="compile.classpath">
        <fileset dir="${lib.dir}">
            <include name="mysql-connector-j-8.2.0.jar"/>
        </fileset>
    </path>

    <target name="-pre-compile">
        <mkdir dir="${build.dir}"/>
    </target>

    <target name="compile" depends="-pre-compile">
        <javac srcdir="${src.dir}" destdir="${build.dir}" classpathref="compile.classpath">
            <include name="**/*.java"/>
        </javac>
    </target>

    <target name="run" depends="compile">
    <echo message="Running with classpath:"/>
    <pathconvert pathsep=";" property="runtime.classpath">
        <path>
            <path refid="compile.classpath"/>
            <pathelement path="${build.dir}"/>
        </path>
    </pathconvert>
    <echo message="${runtime.classpath}"/>
    
    <java classname="bank_management.Bank_management" fork="true">
        <classpath>
            <path refid="compile.classpath"/>
            <pathelement path="${build.dir}"/>
        </classpath>
    </java>
</target>

</project>
